# Generated by Django 4.0.4 on 2022-04-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date_transaction', models.DateTimeField(verbose_name='Data da transação')),
                ('transaction_type', models.IntegerField(choices=[(0, 'Deposito'), (1, 'Saque')], default=0, verbose_name='Tipo da transação')),
                ('digital_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_account.digitalaccount')),
            ],
        ),
    ]
