# Generated by Django 4.0.4 on 2022-04-26 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrier', '0002_alter_carrier_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo')),
                ('number', models.CharField(max_length=9, verbose_name='Número da conta')),
                ('agency', models.CharField(max_length=5, verbose_name='Agência')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier')),
            ],
        ),
    ]
